// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1UjnkFl_SbelQMIjIIdFy-MQudeZoBE',
    appId: '1:760959647657:web:9679fac2b867f98898ceb8',
    messagingSenderId: '760959647657',
    projectId: 'myproject-50cdc',
    authDomain: 'myproject-50cdc.firebaseapp.com',
    storageBucket: 'myproject-50cdc.firebasestorage.app',
    measurementId: 'G-8SRQSZGVE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZAeqgOMNV6b7a08PqlsGrvnEgXAanCc',
    appId: '1:760959647657:android:29b74c643540952098ceb8',
    messagingSenderId: '760959647657',
    projectId: 'myproject-50cdc',
    storageBucket: 'myproject-50cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC63ChEjOuNCwKd3R9cb_mlp6WNDobxDvM',
    appId: '1:760959647657:ios:5f44f0a44afbe55798ceb8',
    messagingSenderId: '760959647657',
    projectId: 'myproject-50cdc',
    storageBucket: 'myproject-50cdc.firebasestorage.app',
    iosBundleId: 'com.example.chatpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC63ChEjOuNCwKd3R9cb_mlp6WNDobxDvM',
    appId: '1:760959647657:ios:5f44f0a44afbe55798ceb8',
    messagingSenderId: '760959647657',
    projectId: 'myproject-50cdc',
    storageBucket: 'myproject-50cdc.firebasestorage.app',
    iosBundleId: 'com.example.chatpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn1UjnkFl_SbelQMIjIIdFy-MQudeZoBE',
    appId: '1:760959647657:web:40f7492ce891113898ceb8',
    messagingSenderId: '760959647657',
    projectId: 'myproject-50cdc',
    authDomain: 'myproject-50cdc.firebaseapp.com',
    storageBucket: 'myproject-50cdc.firebasestorage.app',
    measurementId: 'G-YK139NL31G',
  );
}
